spring:
  datasource:
    validation-query: SELECT 1
    test-on-borrow: true
    url: ${postgres.url}
    username: ${postgres.user}
    password: ${postgres.password}
    driverClassName: ${database.driver:org.postgresql.Driver}

  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
